// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'enter your api key here',
    appId: '1:145050261742:web:5ecb7d7e19cf025ec0fbff',
    messagingSenderId: '145050261742',
    projectId: 'smart-grocery-app-uic',
    authDomain: 'smart-grocery-app-uic.firebaseapp.com',
    storageBucket: 'smart-grocery-app-uic.appspot.com',
    measurementId: 'G-5T993NXL08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'enter your api key here',
    appId: '1:145050261742:android:1f54de8fa1096c71c0fbff',
    messagingSenderId: '145050261742',
    projectId: 'smart-grocery-app-uic',
    storageBucket: 'smart-grocery-app-uic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'enter your api key here',
    appId: '1:145050261742:ios:a08c4a6a3603b0f4c0fbff',
    messagingSenderId: '145050261742',
    projectId: 'smart-grocery-app-uic',
    storageBucket: 'smart-grocery-app-uic.appspot.com',
    iosClientId:
        '145050261742-j31qcfqsbfdej41ki7ckgdalc61qrkp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartGroceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'enter your api key here',
    appId: '1:145050261742:ios:a08c4a6a3603b0f4c0fbff',
    messagingSenderId: '145050261742',
    projectId: 'smart-grocery-app-uic',
    storageBucket: 'smart-grocery-app-uic.appspot.com',
    iosClientId:
        '145050261742-j31qcfqsbfdej41ki7ckgdalc61qrkp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartGroceryApp',
  );
}
